// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_home_screen_screen_init(void)
{
    ui_home_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_home_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_home_screen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_home_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_volume = lv_label_create(ui_home_screen);
    lv_obj_set_width(ui_volume, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_volume, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_volume, 0);
    lv_obj_set_y(ui_volume, 10);
    lv_obj_set_align(ui_volume, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_volume, "Vol: N/A");

    ui_clock = lv_obj_create(ui_home_screen);
    lv_obj_set_width(ui_clock, 140);
    lv_obj_set_height(ui_clock, 60);
    lv_obj_set_align(ui_clock, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clock, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_clock);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "00:00");
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

}
