// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_screen_home_screen_init(void)
{
    ui_screen_home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen_home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen_home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_screen_home, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_time = lv_label_create(ui_screen_home);
    lv_obj_set_width(ui_label_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_label_time, "00:00");

    ui_label_vol_home = lv_label_create(ui_screen_home);
    lv_obj_set_width(ui_label_vol_home, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_vol_home, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_vol_home, 0);
    lv_obj_set_y(ui_label_vol_home, 10);
    lv_obj_set_align(ui_label_vol_home, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_label_vol_home, "");
    lv_obj_set_style_text_font(ui_label_vol_home, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}
