// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT time

lv_obj_t * ui_time_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_time;
    cui_time = lv_label_create(comp_parent);
    lv_obj_set_width(cui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_time, -13);
    lv_obj_set_y(cui_time, 15);
    lv_obj_set_align(cui_time, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_TIME_NUM);
    children[UI_COMP_TIME_TIME] = cui_time;
    lv_obj_add_event_cb(cui_time, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_time, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_time_create_hook(cui_time);
    return cui_time;
}

